export const CONFIG_INITIAL = "CONFIG_INITIAL";

//auth AD
export const SEND_CREDENTIALS = "SEND_CREDENTIALS";
export const SAVE_AUTH_DATA_SUCCESS = "SAVE_AUTH_DATA_SUCCESS";
export const ACTION_AUTH_SUCCESS = "ACTION_AUTH_SUCCESS";
export const MESSAGE_AUTH = "MESSAGE_AUTH";

//promociones
export const GET_ALL_PROMOTIONS = "GET_ALL_PROMOTIONS";
export const SAVE_ALL_PROMOTIONS = "SAVE_ALL_PROMOTIONS";
export const DELETE_PROMOTION_BY_ID = "DELETE_PRMOTION_BY_ID";
export const CREATE_A_NEW_PROMOTION = "CREATE_A_NEW_PROMOTION";

export const SAVE_GENERAL_INFO = "SAVE_GENERAL_INFO";
export const SAVE_HOT_SALE_INFO = "SAVE_HOT_SALE_INFO";
export const SAVE_BENEFICIOS_INFO = "SAVE_BENEFICIOS_INFO";
export const SAVE_DETALLES_INFO = "SAVE_DETALLES_INFO";
export const SAVE_HORARIOS_INFO = "SAVE_HORARIOS_INFO";
export const SAVE_SUBIDA_IMAGEN_INFO = "SAVE_SUBIDA_IMAGEN_INFO";
export const SAVE_CONFIRMACION_INFO = "SAVE_CONFIRMACION_INFO";
export const CHANGE_HOTSALE_BANNER = "CHANGE_HOTSALE_BANNER";
export const ASSIGN_A_NEW_HOT_SALE = "ASSIGN_A_NEW_HOT_SALE";

export const PUT_PROMOTION_DATA = "PUT_PROMOTION_DATA";
export const ACTION_SUCCESS = "ACTION_SUCCESS";

export const TAB_INDEX = "TAB_INDEX";